server:
  port: 8080

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 50
        # 连接池中的最小空闲连接
        min-idle: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: PT-1S
      # 关闭超时时间
      shutdown-timeout: PT0.1S
    # 连接超时时间（毫秒）
    timeout: PT10S